baseURL: "sebastiantillbraun.github.io" 
title: Sebastian Till Braun
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
       # - name: Books
       #   url: books/
       #   weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 4
        - name: Data
          url: data/
          weight: 3
        #- name: Blog
        #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #  weight: 6

params:
    description: "This website hosts Sebastian Braun's CV, research papers, course materials, data, and contact information"
    author: Sebastian Till Braun
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Sebastian Till Braun
          subtitle: "I am a Professor of Economics at the University of Bayreuth, where I hold the chair for Quantitative Economic History (VWL VII). I am also a Research Fellow at the Centre for Research and Analysis of Migration (CReAM), IZA – Institute of Labor Economics, and RWI – Leibniz Institute for Economic Research. Before joining the University of Bayreuth, I was an Associate Professor at the University of St Andrews and a Senior Researcher at the Kiel Institute for the World Economy. I work at the intersection of international and regional economics, labor economics, and quantitative economic history."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: papers/
            - name: Data
              url: data/
            - name: Courses
              url: courses/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/


    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:sebastian.braun@uni-bayreuth.de
        #- name: Location
        #  url: location/
        - name: Office Hours
          url: https://calendly.com/sebastian-braun/officehours
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: Twitter
          url: https://x.com/SebastianTBraun
        - name: Bluesky
          url: https://bsky.app/profile/sebastiantbraun.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Sebastian Till Braun"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2